spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceag
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: luhmgasparetto@gmail.com
    password: kwkz dksh xncq ubsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

mercadopago:
    token: ${MERCADO_PAGO_TOKEN}
