spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: kwkz dksh xncq ubsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}

email:
  author: ${EMAIL_AUTHOR}

efi:
  pix:
    client_id: ${EFI_CLIENT_ID}
    client_secret: ${EFI_CLIENT_SECRET}
    chave: ${EFI_PIX_KEY}
    cert-path: classpath:producao-811858-agenorgasparettoec.p12
    cert-password: ""
    sandbox: false
